services:
  postgres:
    image: postgres:16
    environment:
      POSTGRES_DB: mydb
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password_123456
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./databases:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"

  backend:
    build: ./backend
    environment:
      POSTGRES_DSN: "host=postgres user=admin password=password_123456 dbname=mydb port=5432 sslmode=disable TimeZone=Asia/Shanghai"
    ports:
      - "8080:8080"
    depends_on:
      - postgres

  admin-frontend:
    build: ./admin-frontend
    ports:
      - "3000:80"
    depends_on:
      - backend

  web-frontend:
    build: ./web-frontend
    ports:
      - "3001:80"
    depends_on:
      - backend

volumes:
  postgres_data: 